### ISSUE TITLE
How do I use this plugin?

### ISSUE THREAD

**Issue by galbaras** [niccord/BracketsCheck#12]
I've installed BracketsCheck, but I'm not sure how to use it. Can't find anything online that describes this.

**Comment by ghost** [comment]
I can't figure out how to use this plugin too. I have one missing } somewhere in a file with over 4000 lines, and trying to fix it is actually driving me mad.

**Comment by niccord** [comment]
Hi folks,
I am sorry I wasn't able to provide you with some sort of guide.

This plugin was written with the goal of checking a large SQL file and then evolved a little.

If the brackets in the file are balanced, there's not a lot to say.

On the other hand, there are three cases when a bracket is not matched:
- a bracket opens and it never closes;
- a wrong type of bracket closes (a round one instead of a square one);
- a bracket closes with no opening correspondent.

For the first two scenarios, the plugin returns an error on the opening bracket.
For the last scenario, it returns an error on the bracket itself which should be removed.

**Comment by galbaras** [comment]
Thanks for this, but what I wanted to know is how to make the plugin work on a document and what I can expect to see as its output.

**Comment by niccord** [comment]
You can install this as a Notepad++ plugin, it works on the sheet you are currently displaying.

You can select a part of the text in the document or let the plugin check the entire doc.

If the brackets are balanced, the plugin will show an alert saying all is ok.
Otherwise it points out where it have found an error with a line and char numbers, following the rules I have listed above.

When you think you have fixed the issue, you can lauch again BracketsCheck and see the output.

I hope this clears your doubts @galbaras but if it doesn't, please try to be more specific because I think I am missing something :smile:

**Comment by galbaras** [comment]
Thanks again.

It works very well, although the results don't necessarily point to the problem or the solution, because the plugin doesn't know where brackets are supposed to be, only where the actually are. Cest la vie :)

A couple of ideas, if I may:

1. Rather than just show a dialog box with the line and character number, move the text pointer to that location as well. This will be very helpful

2. Detect the type of document and choose which brackets to check by it. For example, angle brackets do not need to match in CSS files, but they do need to match in a HTML file

Thanks again!

**Comment by niccord** [comment]
Although I don't think the second of your proposals is something I want to achieve at the moment, feel free to submit a PR to the first one.

Cheers!

**Comment by galbaras** [comment]
Unfortunately, doing this is not within my skillset :disappointed:
