### ISSUE TITLE
Unbalanced bracket in commented line

### ISSUE THREAD

**Issue by Pr0metheus2** [niccord/BracketsCheck#17]
The plugin does not accepting brackets in commented line, e.g.  **// {** and says "Brackets unbalanced...", but on different line of the script, so its almost impossible to find error.

**Comment by niccord** [comment]
Hi @Pr0metheus2 thanks for submitting the issue, can you please provide a minimal reproducible example of the error?

This will help me a lot in investigating the bug.

Cheers

**Comment by Pr0metheus2** [comment]
![check](https://github.com/niccord/BracketsCheck/assets/9161285/bdbd7c8d-4ece-43fd-847c-f15bbe2537cb)
Problem(!) is on line 17, which should be ignored due to commented line, so never processed by the script.

**Comment by Pr0metheus2** [comment]
[bracket.txt](https://github.com/niccord/BracketsCheck/files/11882927/bracket.txt)
Source file for testing

**Comment by niccord** [comment]
Thank you!
The problem is that the parenthesis at line 18 matches the one at line 17, so the first one at line 1 results unmatched.
That's why you have a wrong error message.

It is not simple to ignore commented lines because the plugin doesn't know which language you're using.
Even knowing the language, it should know how a comment can be expressed in each language.

For the current time, I can only suggest the following workaround if you encounter this issue again for the current release:
try unchecking all the parenthesis types in the configuration, then enable them one by one and check which one is causing the issue.

**Comment by Pr0metheus2** [comment]
I understand that the problem is detection of language used, so it seems the only solution to solve such problem is to perform workaround you have suggested.

If plugin has access to file name, this could be potential solution. As my file is .js, plugin could assume that language used in file is JavaScript, which has comment as double slash (//) and vice versa.

But anyway, thanks for your help.
